#Get all tables and columns that has a foreign key to DB.TABLE.COLUMN

SELECT 
  TABLE_NAME,COLUMN_NAME
FROM
  INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
  REFERENCED_TABLE_SCHEMA = 'DATABASE' AND
  REFERENCED_COLUMN_NAME = 'COLUMN';
